### ISSUE TITLE
tlogclient (in tlogStorage) fails at master (c56f16a): max send retry reached

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#265]
logs:

```
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:36976" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:41888" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:42736" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:37965" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="Started listening on local address 127.0.0.1:39693" module=global caller=server.go:55
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:36231" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:42928" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:37918" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=dbug msg="received handshake request from incoming connection" module=global caller=server.go:140
t=2017-06-11T13:29:15+0000 lvl=dbug msg="incoming connection checks out with version: 1.1.0-alpha" module=global caller=server.go:150
t=2017-06-11T13:29:15+0000 lvl=dbug msg="create vdisk with expectedSequence:0" module=global caller=vdisk.go:147
t=2017-06-11T13:29:15+0000 lvl=info msg="vdisk a reset first sequence to 0" module=global caller=vdisk.go:222
t=2017-06-11T13:29:15+0000 lvl=dbug msg="handshake phase successfully completed" module=global caller=server.go:175
t=2017-06-11T13:29:15+0000 lvl=dbug msg="replying handshake with status: OK" module=global caller=server.go:202
t=2017-06-11T13:29:15+0000 lvl=dbug msg="vdisk a's tlog server has received force flush message" module=global caller=tlog.go:284
t=2017-06-11T13:29:15+0000 lvl=dbug msg="vdisk a's tlog server has received force flush message" module=global caller=tlog.go:284
panic: tlogStorage couldn't send block 0 (seq: 0): max send retry reached
goroutine 20097 [running]:
github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).transactionSender(0xc4204087e0, 0x118aba0, 0xc4208186c0)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:322 +0x2b9
created by github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).GoBackground
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:260 +0xc2
FAIL	github.com/zero-os/0-Disk/nbdserver/ardb	25.680s
```

Job: https://travis-ci.org/zero-os/0-Disk/jobs/241728348

```
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:36976" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:41888" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:42736" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:37965" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="Started listening on local address 127.0.0.1:39693" module=global caller=server.go:55
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:36231" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:42928" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:37918" module=global caller=redis.go:47
t=2017-06-11T13:29:15+0000 lvl=dbug msg="received handshake request from incoming connection" module=global caller=server.go:140
t=2017-06-11T13:29:15+0000 lvl=dbug msg="incoming connection checks out with version: 1.1.0-alpha" module=global caller=server.go:150
t=2017-06-11T13:29:15+0000 lvl=dbug msg="create vdisk with expectedSequence:0" module=global caller=vdisk.go:147
t=2017-06-11T13:29:15+0000 lvl=info msg="vdisk a reset first sequence to 0" module=global caller=vdisk.go:222
t=2017-06-11T13:29:15+0000 lvl=dbug msg="handshake phase successfully completed" module=global caller=server.go:175
t=2017-06-11T13:29:15+0000 lvl=dbug msg="replying handshake with status: OK" module=global caller=server.go:202
t=2017-06-11T13:29:15+0000 lvl=dbug msg="vdisk a's tlog server has received force flush message" module=global caller=tlog.go:284
t=2017-06-11T13:29:15+0000 lvl=dbug msg="vdisk a's tlog server has received force flush message" module=global caller=tlog.go:284
panic: tlogStorage couldn't send block 0 (seq: 0): max send retry reached

goroutine 20097 [running]:
github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).transactionSender(0xc4204087e0, 0x118aba0, 0xc4208186c0)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:322 +0x2b9
created by github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).GoBackground
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:260 +0xc2
FAIL	github.com/zero-os/0-Disk/nbdserver/ardb	25.680s
```

Job: https://travis-ci.org/zero-os/0-Disk/jobs/241728347

**Comment by GlenDC** [comment]
Linked jobs succeed now though, as I restarted them ONCE, and then they did work. So I guess it's another one of those issues where it makes the Travis CI tests fail now and then.

**Comment by GlenDC** [comment]
Latest commit (eb7fbf2) failed at the same issue, this time during Travis CI's `make test -race`. So shouldn't be too hard to reproduce after all. Your computer might be too fast to reproduce it locally though, not too sure.

I think first good step would be to add a new minimal test case to be able to reproduce this issue 100% of the time. This way you have somewhere to start from.

**Comment by iwanbk** [comment]
This issue is caused by the addition of `client.stopped` not returning proper error value and it exposes another issue in nbdserver:
- 381450125ba85040d7a27032218ecf9be4b301b1 fix the error value
- the issue in nbdserver is that it tries to call `client.Send` on closed client. https://travis-ci.org/zero-os/0-Disk/jobs/241867934. It is caused by the race of `ctx.Done()` and `transasctionCh` channel on `transactionSender` goroutine. I think it is harmless issue, can be easily solved by better error handling.
