### ISSUE TITLE
TestResetFirstSequence sometimes seem to deadlock

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#275]
https://travis-ci.org/zero-os/0-Disk/jobs/242714975
https://api.travis-ci.org/jobs/242714975/log.txt?deansi=true
https://gist.github.com/iwanbk/cf9474d29e9b3d17b17e3ef085662745

```
goroutine 733 [chan receive, 4 minutes]:
github.com/zero-os/0-Disk/tlog/tlogserver/server.TestResetFirstSequence(0xc428fd1520)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/reset_first_seq_test.go:69 +0x44e
testing.tRunner(0xc428fd1520, 0xd632a8)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:697 +0x2ca

```

```
goroutine 786 [IO wait, 4 minutes]:
net.runtime_pollWait(0x2ab20c754378, 0x72, 0x11784e0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200ef1e8, 0x72, 0x1173770, 0xc42000c780)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200ef1e8, 0xffffffffffffffff, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4200ef180, 0x0, 0x1176ca0, 0xc42000c780)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc420091748, 0xc420725f30, 0xb7b076, 0x458080)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420091748, 0xd63228, 0x1181060, 0xc42000ec90, 0xc42bda1540)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock.go:228 +0x49
github.com/zero-os/0-Disk/tlog/tlogserver/server.(*Server).Listen(0xc42bda1540)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/server.go:85 +0x69
created by github.com/zero-os/0-Disk/tlog/tlogserver/server.TestResetFirstSequence
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/reset_first_seq_test.go:37 +0xf9
```

**Comment by iwanbk** [comment]
might related to #241

**Comment by iwanbk** [comment]
Only happen on travis, can't reproduce it

**Comment by GlenDC** [comment]
Seems suspicious that this issue is closed without a fix. Did this ever occur again on travis @iwanbk?

**Comment by iwanbk** [comment]
happens again today on travis, not sure if it worth to fix considering we will remove this feature anyway.
see #319

**Comment by GlenDC** [comment]
No for now that's fine I think, in case we decide later we don't remove this feature, than we do have to fix this. But for now it's OK.

**Comment by GlenDC** [comment]
This issue triggered again today a failure on travis. I'll be happy when this is gone...

**Comment by iwanbk** [comment]
Yeah, it needs #273, and not just the issue, but the test itself will be gone
