### ISSUE TITLE
TestForceFlushAtSeq times out in Travis's `make testgo`

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#344]
The `TestforceFlushAtSeq` seems to have timed out in master (e32d95e).

Here is a log snippet that might highlight the issue:

```
goroutine 806 [IO wait, 4 minutes]:
net.runtime_pollWait(0x2b8c09183670, 0x72, 0x11b54e0)
/* .................................... */
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/tcpsock.go:228 +0x49
github.com/zero-os/0-Disk/tlog/tlogserver/server.(*Server).Listen(0xc42cf85020, 0x11b9c60, 0xc42814d080)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/server.go:89 +0xd5
created by github.com/zero-os/0-Disk/tlog/tlogserver/server.TestResetFirstSequence
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/reset_first_seq_test.go:40 +0x16d

goroutine 841 [IO wait, 4 minutes]:
net.runtime_pollWait(0x2b8c09184c58, 0x72, 0xe8)
/* .................................... */
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/encoding/binary/binary.go:170 +0xea
github.com/zero-os/0-Disk/tlog.ReadCheckMessageType(0x11b2020, 0xc42d6444e0, 0xc42cf85020, 0x11b9c60, 0xc42d3d9300)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/message_type.go:40 +0x9c
github.com/zero-os/0-Disk/tlog/tlogserver/server.(*Server).handle(0xc42cf85020, 0xc42000f0e8, 0x0, 0x0)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/server.go:248 +0x26d
github.com/zero-os/0-Disk/tlog/tlogserver/server.(*Server).Listen.func1(0x11be120, 0xc42000f0e8, 0xc42cf85020, 0xc42000f0e8)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/server.go:110 +0x9b
created by github.com/zero-os/0-Disk/tlog/tlogserver/server.(*Server).Listen
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/server.go:116 +0x1a2

goroutine 856 [IO wait, 4 minutes]:
/* .................................... */
	/home/travis/gopath/src/github.com/zero-os/0-Disk/vendor/zombiezen.com/go/capnproto2/mem.go:471 +0x89
github.com/zero-os/0-Disk/tlog/tlogclient.(*Client).decodeBlockResponse(0xc421bfb1e0, 0x11b3420, 0xc42000f000, 0x0, 0xc42d404e28, 0x405f0b)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogclient/capnp.go:92 +0x7b
github.com/zero-os/0-Disk/tlog/tlogclient.(*Client).recvOne(0xc421bfb1e0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogclient/client.go:353 +0xcf
github.com/zero-os/0-Disk/tlog/tlogclient.(*Client).Recv.func1(0xc421bfb1e0, 0xc42d6445a0)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogclient/client.go:287 +0x7c
created by github.com/zero-os/0-Disk/tlog/tlogclient.(*Client).Recv
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogclient/client.go:328 +0x67

goroutine 857 [sleep]:
time.Sleep(0x5f5e100)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/time.go:59 +0xf9
github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer.(*Buffer).TimedOut.func1(0x11b9c60, 0xc42d3d91c0, 0xc42d6442a0)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer/buffer.go:217 +0x140
created by github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer.(*Buffer).TimedOut
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer/buffer.go:233 +0x53
FAIL	github.com/zero-os/0-Disk/tlog/tlogserver/server	300.046s
```

You can find the full (did filter out ledisdb goroutines and some OS stuff) at: https://gist.github.com/GlenDC/4ccb939eb0e6d1e88401c508747ac0e0

**Comment by iwanbk** [comment]
I wonder why there are two actives test here : TestResetFirstSequence & TestForceFlushAtSeq

**Comment by iwanbk** [comment]
So, i know this failed test yesterday when working at TestSlaveSync, but i thought it was TestResetFirstSequence (because this was what i found in this super long log) which we agreed need not to be solved.

If it is `TestForceFlushAtSeq`, i wonder if it is the same issue as TestSlaveSync

**Comment by GlenDC** [comment]
I'm fairly sure it is `TestForceFlushAtSeq` in this case, based on the fact that it's the only `_test.go` file (and line position) that was mentioned in the open goroutines of the log.

**Comment by iwanbk** [comment]
As discussed on telegram, TestResetFirst also has open goroutine.

I checked TestForceFlush, there are two lines of code mentioned in the error log
```
github.com/zero-os/0-Disk/tlog/tlogserver/server.(*Server).Listen(0xc421785800, 0x11b9c60, 0xc4202c1300)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/server.go:89 +0xd5
created by github.com/zero-os/0-Disk/tlog/tlogserver/server.TestForceFlushAtSeq
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/force_flush_test.go:30 +0x141
```
and
```
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/server.go:89 +0xd5
created by github.com/zero-os/0-Disk/tlog/tlogserver/server.testForceFlushAtSeqPossibleRace
	/home/travis/gopath/src/github.com/zero-os/0-Disk/tlog/tlogserver/server/force_flush_test.go:102 +0x14a
```

Both lines in force_flush_test.go calling tlog sever `Listen`, see:
-  `https://github.com/zero-os/0-Disk/blob/e32d95e6e0d288f5d9599dc3a84dfa3f6d7d082a/tlog/tlogserver/server/force_flush_test.go#L30`
- https://github.com/zero-os/0-Disk/blob/e32d95e6e0d288f5d9599dc3a84dfa3f6d7d082a/tlog/tlogserver/server/force_flush_test.go#L102

And in the server.go, it is line that call `net.Accept`, see https://github.com/zero-os/0-Disk/blob/e32d95e6e0d288f5d9599dc3a84dfa3f6d7d082a/tlog/tlogserver/server/server.go#L89

So, i see no issue here.

I suggest to close this issue.

I can check TestResetFirst today, see if i can do something

**Comment by GlenDC** [comment]
>  can check TestResetFirst today, see if i can do something

Is there already an issue open for that?

**Comment by iwanbk** [comment]
> Is there already an issue open for that?

Yep, geert closed it and we agreed to not solve it because the feature tested will be removed, feel free to reopen

**Comment by iwanbk** [comment]
Found it, #275
