### ISSUE TITLE
index out of range in Storage/cluster.go during unit test

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#590]
```
?   	github.com/zero-os/0-Disk/nbd/ardb/command	[no test files]
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:33886" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster foo started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for foo stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:40110" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:38964" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster foo started" module=global caller=config_api.go:386
20::{"status":422,"subject":"ardb","data":{"address":"127.0.0.1:38964","db":0,"type":"primary","vdiskID":"foo"}}
t=2017-11-02T23:24:35+0000 lvl=dbug msg="updating vdisk foo' primary server #1 state to offline" module=global caller=cluster.go:193
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for foo stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:36996" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:32953" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster foo started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for foo received config bytes from source" module=global caller=config_api.go:270
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for foo received config bytes from source" module=global caller=config_api.go:402
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for foo stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:46651" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:40371" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:33104" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:38812" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster foo started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster bar started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 0 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 1 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 2 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 3 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 4 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 5 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 6 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 7 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:45467" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:34345" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 0 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 2 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 4 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 6 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
20::{"status":422,"subject":"ardb","data":{"address":"127.0.0.1:33104","db":0,"type":"template","vdiskID":"foo"}}
t=2017-11-02T23:24:35+0000 lvl=dbug msg="updating vdisk foo' template server #1 state to offline" module=global caller=cluster.go:570
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for bar stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for foo stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:36973" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:38061" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:40836" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:38130" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster foo started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster bar started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 0 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 1 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 2 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 3 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 4 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 5 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 6 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 7 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for foo received config bytes from source" module=global caller=config_api.go:270
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for foo received config bytes from source" module=global caller=config_api.go:402
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for foo received config bytes from source" module=global caller=config_api.go:270
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for bar received config bytes from source" module=global caller=config_api.go:402
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:39170" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:38192" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 0 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 2 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 4 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 6 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for bar stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for foo stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:33637" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:33940" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:45969" module=global caller=ledisdb.go:70
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster foo started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo started" module=global caller=config_api.go:254
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig for cluster bar started" module=global caller=config_api.go:386
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 0 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 1 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 2 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 3 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 4 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 5 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 6 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="block 7 not available in primary storage, but did find it in template storage" module=global caller=nondeduped.go:137
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for foo stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
t=2017-11-02T23:24:35+0000 lvl=dbug msg="WatchStorageClusterConfig cluster for bar stopped" module=global caller=config_api.go:393
t=2017-11-02T23:24:35+0000 lvl=dbug msg="watchVdiskNBDConfig for vdisk foo stopped" module=global caller=config_api.go:261
20::{"status":400,"subject":"ardb","data":{"address":"127.0.0.1:33940","db":0,"type":"primary","vdiskID":"foo"}}
panic: runtime error: index out of range
goroutine 335 [running]:
github.com/zero-os/0-Disk/nbd/ardb/storage.(*PrimaryCluster).handleServerStateUpdate(...)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/ardb/storage/cluster.go:199
github.com/zero-os/0-Disk/nbd/ardb/storage.(*PrimaryCluster).updateServerState(0xc420501da0, 0x1, 0x1162c01, 0x0, 0x0)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/ardb/storage/cluster.go:188 +0x3b5
github.com/zero-os/0-Disk/nbd/ardb/storage.(*PrimaryCluster).doAt(0xc420501da0, 0x1, 0xc4221232b0, 0xf, 0x0, 0x0, 0x17bed80, 0xc420425320, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/ardb/storage/cluster.go:152 +0x203
github.com/zero-os/0-Disk/nbd/ardb/storage.(*PrimaryCluster).DoFor(0xc420501da0, 0x7, 0x17bed80, 0xc420425320, 0x3, 0x3, 0xc420425320, 0xc42002d300)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/ardb/storage/cluster.go:73 +0x224
github.com/zero-os/0-Disk/nbd/ardb/storage.(*nonDedupedStorage).SetBlock(0xc4200b61c0, 0x7, 0xc4200f4cb8, 0x8, 0x8, 0xc420035fc8, 0xf6aaf4)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/ardb/storage/nondeduped.go:69 +0x24f
github.com/zero-os/0-Disk/nbd/ardb/storage.(*nonDedupedStorage).getPrimaryOrTemplateContent.func1(0xc4200b61c0, 0x7, 0xc4202f3240)
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/ardb/storage/nondeduped.go:128 +0x94
created by github.com/zero-os/0-Disk/nbd/ardb/storage.(*nonDedupedStorage).getPrimaryOrTemplateContent
	/home/travis/gopath/src/github.com/zero-os/0-Disk/nbd/ardb/storage/nondeduped.go:127 +0x805
FAIL	github.com/zero-os/0-Disk/nbd/ardb/storage	0.626s
```

@ master (e3e558fa37ce310eec0a398ed62207fb37feab23)

**Comment by GlenDC** [comment]
The problem seems to be that in the (primary) storage Clusters we are working with a cached serverIndex which is for some window not protected by a lock at:

https://github.com/zero-os/0-Disk/blob/1627a766fe4a06cbd75a5019078194e41ef8728c/nbd/ardb/storage/cluster.go#L122-L148

Than suddenly we might use that cached server index to update the server state a bit below (in case the server needs to be marked as offline): https://github.com/zero-os/0-Disk/blob/1627a766fe4a06cbd75a5019078194e41ef8728c/nbd/ardb/storage/cluster.go#L152-L154

Within the `updateServerState` it will be protected behind a lock there once again before trying to read/write, so there is no way that the race checker will ever be able to catch the mistake that's going on here

However the problem is that during that window where there is no lock the servers could have been modified. In the scenario of this issue that probably has happened to a server count smaller than previously, and thus we get an OOB. But even if we don't get such a panic, that would be even worse as we might be modifying (silently) a wrong server.

The easiest and most drastic solution would be to work with a single `sync.Mutex`, and lock (only) at all public functions (plus also at the gorotuine updater) of these cluster types. It would prevent from such windows to exist. It would however make the cluster a lot less performant, as we would only be able to execute on action per cluster at the same time, making a vdisk essentially single-threaded. I don't think that's something we want to go for, so we'll need some time to come up with a better plan to fix this mess.

**Comment by GlenDC** [comment]
Note sure if related, but another test failed out of the blue (probably due to async issues):

```
--- FAIL: TestTemplateServerFails (0.03s)
	Error Trace:	cluster_test.go:294
	Error:      	Not equal: 
	            	expected: *errors.errorString(&errors.errorString{s:"server is unavailable"})
	            	actual: <nil>(<nil>)
```
